### ISSUE TITLE
The TestPaniq scene displays a black screen

### ISSUE THREAD

**Issue by mmmovania** [mmacklin/tinsel#3]
First up, thanks for sharing this great library. One issue though the nature.hdr probe is missing due to which the TestPaniq scene displays a black screen. If possible do share the nature.hdr file that you used or atleast share the URL or the name of the hdr file used so that the results may be replicated.
The hdr file I used is [phalzer_forest_01_4k.hdr from polyhaven](https://polyhaven.com/a/phalzer_forest_01) which gives similar results as shown below.
![image](https://user-images.githubusercontent.com/1354859/127470183-0aa21f3e-5004-4334-a5f3-d2b6010f7391.png)

Thanks,
MMMovania

**Comment by mmacklin** [comment]
Hi there,

I don't recall exactly where I got that file - but you can find many nice
HDR maps online, I used this one in the past:
http://www.hdrlabs.com/sibl/archive.html

Cheers,
Miles

**Comment by mmmovania** [comment]
Thanks for the link.
